# Generated by Django 5.2.5 on 2025-08-13 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='hourly_rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='core.subject'),
        ),
    ]
